void reverse(char *str, int len);
int  atoi(char *str);
char* itoa(int num);
char *ultohex(unsigned long num);
int strlen(const char *s);
int strcmp(const char *s1, const char *s2);
char *strcpy(char *des, const char *src);
char *strncpy(char *des, const char *src, size_t n);
int strncmp(const char *s1, const char *s2, int len);
void *memcpy(void *dest, void *src, size_t n);
char* strstr(char *str1, char *str2);
void reverse(char *str, int len);
void *memset(void *s, int c, size_t n);
char* itoa(int num);
int  atoi(char *str);
char* ultohex(uint64_t num);
char *itohex(int a);
